### PR TITLE
Unit test failures fix

### PR DESCRIPTION
**Pull request by francis-nijay**
# Description
Fix unit tests that were failing for some time in fc, iscsi and nvme

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1469 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Unit test run successfully without failures

### CODE REVIEW

**Review by donatwork — APPROVED** [review]

**Comment by adarsh-dell** [comment]
Can see some panic in the log. I believe we should handle it properly.
image

**Comment by adarsh-dell** [comment]
> Can see some panic in the log. I believe we should handle it properly. image

As per the github action this will run the UT of all packages but make test will only cover 2 packages.
image
image

**Comment by francis-nijay** [comment]
Fixing the test failures in other packages is in progress. Will run all tests from github actions preferably

**Comment by adarsh-dell** [comment]
Ran UT locally for all packages:

image

**Review by donatwork — APPROVED** [review]
Good job getting these fixed. Thanks.

**Review by suryagupta4 — APPROVED** [review]

**Pull request merged**
